on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: rush build

      - name: Run tests
        run: rush test
