on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Pnpm
        run: npm install -g pnpm
          
      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Install dependencies
        run: rush install

      - name: Run build
        run: rush build

